### ISSUE TITLE
Support for all minidrone functions

### ISSUE THREAD

**Issue by moe-the-fabber** [gandhimonik/DroneJS#4]
hey gandhi
i wondered if you could add the other drone functions
like picture taking and claw and tool actions of the mambo 
parrot.

regards

**Comment by gandhimonik** [comment]
Hey moe-the-fabber,

The current API supports taking picture from the drone. Also downloading and deleting the pictures is available.

About the claw and tool actions of Parrot Mambo, I am still working on it and will let you know when its available.
